language: python

python:
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.5"

before_install:
  - pip install codecov

install:
  - pip install -r requirements.txt

script:
  - coverage run --source colador -m unittest discover -s tests

after_success:
  - codecov